server:
  port: 3232

spring:
  application:
    name: api-proxy 
  
eureka:
  client:
     service-url:
      defaultZone: http://localhost:8761/eureka  

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  host:
    socket-timeout-millis: 2000000
  ribbon:
     eager-load:
      enabled: true
 
  routes:
    recomend-service:
       path: /recomend-service/**
       url: http://localhost:7070/
        
 

