server:
  port: 3030

spring:
  application:
    name: loan-processing-service   
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer1:8765/eureka
