server:
  port: 2020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: srivatsan
   
    
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
---

spring:
  profiles:
  - "inmem"    
  datasource:
    url: jdbc:h2:file:C:/h2data/sample
    driver-class-name: org.h2.Driver
    username: sa
    password:    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
server:
  port: 2022
 
 