
spring:
  profiles:
  - peer1
  application:
    name: eureka-clustering
server:
  port: 8765

  
eureka:
  instance:
    hostname: eureka-peer1
    appname: eureka-clustering
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer2:8770/eureka  

---
spring:
  profiles:
  - peer2
  application:
    name: eureka-clustering  

server:
  port: 8770

  
eureka:
  instance:
    hostname: eureka-peer2
    appname: eureka-clustering
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-peer1:8765/eureka  
    